#! /bin/bash

CODE_FOLDER=~/code/

cd $CODE_FOLDER

rproj="$(ls -d -- */*/.git | xargs -L1 "dirname" | fzf)"

proj="$(basename "$rproj" | tr . _)"

if [[ -z $rproj ]]; then
    exit 0
fi





cd $rproj

if ! tmux has-session -t=$proj 2> /dev/null; then
  tmux new-session -ds $proj "nvim ." 
    tmux split-window -hl 15
fi

if [[ -z $(env | grep tmux) ]]; then
  tmux a -t $proj
else
  tmux switch-client -t $proj

fi
